""" "add_radio_programs_table"

Revision ID: 740af7d90bcc
Revises: 
Create Date: 2023-10-14 05:42:41.355916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '740af7d90bcc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('radio_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('program_id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('air_date', sa.Date(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('spotify_playlist', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_radio_programs_id'), 'radio_programs', ['id'], unique=False)
    op.create_index(op.f('ix_radio_programs_program_id'), 'radio_programs', ['program_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_radio_programs_program_id'), table_name='radio_programs')
    op.drop_index(op.f('ix_radio_programs_id'), table_name='radio_programs')
    op.drop_table('radio_programs')
    # ### end Alembic commands ###
