version: "3.8"

x-logging: &logging
  driver: "json-file"
  options:
    max-file: "5"
    max-size: 10m

services:
  audio-api:
    image: audio_api:dev
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: development
    logging: *logging
    init: true
    ports:
      - 3000:3000
    tty: true
#    command: sleep infinity
    volumes:
      - ../src/audio_api:/app/audio_api
      - ../tests:/app/tests
      - ../cli/manage.py:/app/cli/manage.py
#      - ../alembic:/app/alembic

      # Mount poetry files to edit them from inside the container
      - ../pyproject.toml:/app/pyproject.toml
      - ../poetry.lock:/app/poetry.lock
    env_file:
      - ../config/api.env
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - SERVICES=s3,dynamodb
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/tmp/localstack/data
      - AWS_DEFAULT_REGION=us-east-2
    volumes:
      - "./aws:/etc/localstack/init/ready.d"  # Create buckets and tables scripts
      - "/var/run/docker.sock:/var/run/docker.sock"
